#总开关
enabled: true

#你需要什么功能就配置什么,用不到的功能就直接不配置就行
#例如下面这个配置就代表苦力怕爆炸不破坏方块,然后下面是生效的世界.
#要继续添加功能就继续配置就行,就像下面第二个配置一样,一直叠下去就好
#可以在这里查看支持的功能:https://github.com/Flock-YT/WorldSafe/blob/master/README.md

#苦力怕爆炸不破坏方块
creeperExplosionProtection:
  - world
  - world_nether
  - world_the_end

#TNT爆炸不破坏方块
tntExplosionProtection:
  - world
  - world_nether
  - world_the_end

