# Main Switch / 总开关
enabled: true

# Allow bStats to collect plugin data / 允许 bStats 收集插件数据
enabled-bstats: true

# Configure only the features you need by listing the worlds that should enable them.
# Example / 示例：
# creeperExplosionProtection:
#   - world
#   - world_nether
#   - world_the_end

# Block-related protections / 方块相关功能
bedExplosionCancel: []
respawnAnchorExplosionCancel: []
tntExplosionCancel: []

bedExplosionProtection: []
respawnAnchorExplosionPrevention: []
tntExplosionProtection: []

cropTrampleProtection: []
dragonEggTeleportationPrevention: []

# Entity-related protections / 实体相关功能
creeperExplosionCancel: []
endCrystalExplosionCancel: []
ghastExplosionCancel: []
witherExplosionCancel: []

creeperExplosionProtection: []
endCrystalExplosionPrevention: []
ghastExplosionProtection: []
witherExplosionProtection: []

enderDragonBlockDestructionProtection: []
enderManBlockPickupProtection: []
phantomDamagePrevention: []
